- package.json
`npm` complains about this on install.
> Fix package.json license format

- package.json
This is to fix some failing tests. It's a dirty hack, since simplesmtp is obsolete, but it'll work for now while we have bigger issues.
> Bump simplesmtp version

- lib/dialback.js
When dialback requests are made by pump, it doesn't include the Content-Length. This adds the Content-Length HTTP header to those requests.
> Add the Content-Length to dialback posting client

- public/javascript/about.html
- public/javascript/pump.js
- public/javascript/pump/auth.js
- public/javascript/pump/model.js
- public/javascript/pump/router.js
- public/javascript/pump/socket.js
- public/javascript/pump/view.js
- public/template/layout.utml
For client javascript code written by E14N add stylized comments around license notice. For 3rd party code verbatim copied from other projects create JavaScript Web Labels table and keep scripts code unchanged.
With this changes [LibreJS](https://www.gnu.org/software/librejs/) plugin would not block scripts on pump.io servers.
> Support librejs browser plugin.

- public/template/major-activity-page.utml
all the other calls to partial with headless: false are formatted as {headless: false}. So add missing {
> Add missing { to a dictionary definition

- public/template/replies.utml
Somehow googlebot would try to access an activity without any replies and the server would crash. I wrapped that part of the template to make sure it only gets called when items was defined.
> only iterate over replies.items if it exists.

- lib/model/activity.js
A simple fix for #819. It can probably be made in a more elegant way, but this one seems to work well.
It just checks that the string in 'displayName' is not empty, because if it is, activities descriptions regarding the "null-named" object get broken.
Up to date version, instead of PR #1126.
> Fix for #819, take two

- public/robots.txt
This is a resubmission of PR #533 to fix #526. It adds a robots.txt file to prevent search bots poking around in `/api/`.
@strugee
> Fix #526 - Adds a robot.txt file to disallow to /api/

- public/javascript/pump/view.js
Closes: #1271 
Other option is hide all dropdown's on page change
```javascript
Pump.router.on("route", function() {
// Hide all dropdown open on page change
$(".dropdown.open").trigger("click");
});
```
> Fix close user dropdown when link is clicked

- public/template/main-client.jade
In some resolutions the 'user guide' text in main page looks very tight.
> Fix tight text in main page

- README.md
Installing databank drivers as a normal dependency works fine, they don't
need to be installed inside databank module.
> Simplify databank driver install instructions

- public/template/messages.jade
- public/template/notifications.jade
Fallback text if notifications/messages panel is empty,
disabled button removed because it looks like an error
and displaying alternative text is a normal behavior
in all platforms with notifications panel.
Closes: #1096
> Fallback text if notifications/messages panel is empty

- lib/nicknameblacklist.js
All of these conflict with well-known URLs that we use or may use in
the future. It's not hard to imagine us deciding we won't use some of
these, but better to be restrictive now and open it up later, rather
than dealing with someone potentially signing up with one of these
names.
> Expand list of blacklisted nicknames

- public/template/layout.jade
This causes it to work better when `appendFooter` is used.
Signed-off-by: Jason Self <j@jxself.org>
> Add period and space after owner information

- lib/pumpsocket.js
use `_.fromPairs` instead `_.zipObject` for get same behavior of `underscore.object`,  because are pairs arrays.
Closes: #1474
> Fix get credentials for socket

- routes/uploads.js
- test/upload-file-test.js
`app.session` instance not exists
before pump 4.x `session` middleware was living in `app` instance > [app.js](https://github.com/pump-io/pump.io/commit/79d2478365bb481606d4fd02e908e9ba59421213)
Closes: #1435
> Fix wrong session validation in uploads

- public/stylesheet/pumpio.css
Rebased version of #1140 since the original author is unresponsive
> Small fix in CSS, to break long contents in multiple lines

- public/template/welcome.jade
The site is dead and it has a lot of advertisement, looks like spam and is not good invite the user a spam page.
closes: #1585
> Remove reference to dead site http://openfarmgame.com

- lib/model/activityobject.js
- test/activityobject-validation-test.js
Fixes #801. @ian-kelling, mind trying this branch on your instance since you seem to be running alphas anyway? If you're using npm to install you can switch to this branch with `npm install -g pump-io/pump.io#upstreamduplicates-is-not-an-array`.
> Fix "upstreamDuplicates is not an array" with identi.ca people

- bin/pump
Fixes #1555. This is particularly important since Node's require() has to actively execute each module required, and we don't want just any module in the dep tree to be able to run arbitrary code as root on the administrator's system.
As a bonus, this improves startup performance; `time node -r ./lib/app -e true` reports 3.341s total whereas `time node -e true` reports only 0.092s total. That means we shaved off a little under three and a half seconds from startup.
> Reduce the amount of code we load as root

- public/javascript/pump/view.js
- public/template/lib/responses.jade
* Don't show the reply button on comment pages, to discourage commenting on a comment; see #1645
* Show the original post for comments, to encourage replying to that instead; see #1644
This is ready to go in, but I wanted to get feedback on the design. Here's one that's in reply to a note; notice how the note has been truncated because it's over 80 characters:
And here's an image with a title and no caption:
The "_(Image)_" placeholder is intentional; I thought putting the actual image in the page would steal focus, take up too much space, etc...
If there's a title, it's always shown. Same with content. If there's no content nothing special happens unless it's an image, in which case it gets "_(Image)_".
> Comment page improvements

- .travis.yml
- CHANGELOG.md
- npm-shrinkwrap.json
- package.json
- test/app-e2e-test.js
- test/email-notification-e2e-test.js
- test/lib/email.js
- test/mailer-unit-test.js
- test/plugin-e2e-test.js
- test/register-email-required-e2e-test.js
- util/docker-candidacy.sh
Acording with our [policy ](https://github.com/pump-io/pump.io/wiki/Node.js-version-support) we should add support for the current/LTS node version and drop the EOL version 
Also closes #1118
> Add support to Node 10,12 and 13 drop support to 4 -> 9

- .travis.yml
Tagging as semver-major because I don't want us to ship a release that appears to support Node 13.
> Drop Node 13 and test on Node 14

- public/javascript/pump/socket.js
After some test when the user has a long time disconnected show an error of transports, I add a validation for that ([previously removed](https://github.com/vxcamiloxv/pump.io/blob/9faa5cd8daba7b704a7f3e34abd60aafc7fba7a9/public/javascript/pump/socket.js#L168)) to verify if an error about browser support or a connection problem.
**error:**
> Validate socket if a browser support or a connection problem
